accounts/urls.py
from django.urls import path
from accounts.views import user_login, user_logout, signup
from projects.views import list_projects


urlpatterns = [
    path("", list_projects, name="list_projects"),
    path("signup/", signup, name="signup"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
]

projects/urls.py
from django.urls import path
from .views import list_projects, show_project, create_project


urlpatterns = [
    path("", list_projects, name="list_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path("create/", create_project, name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import show_my_tasks, create_task


urlpatterns = [
    path("mine/", show_my_tasks, name="show_my_tasks"),
    path("create/", create_task, name="create_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from projects.views import list_projects


def redirect_to_home(request):
    return redirect("/projects/")


urlpatterns = [
    path("", redirect_to_home, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="projects",
        null=True,
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name="tasks"
    )
    assignee = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="tasks"
    )

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput())


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirmation = forms.CharField(widget=forms.PasswordInput())

    def clean_password_confirmation(self):
        password = self.cleaned_data.get("password")
        password_confirmation = self.cleaned_data.get("password_confirmation")

        if (
            password
            and password_confirmation
            and password != password_confirmation
        ):
            raise ValidationError("The passwords do not match.")

        return password_confirmation

projects/forms.py
from django import forms
from projects.models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ["is_completed", "owner"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from accounts.forms import LoginForm, SignUpForm
from tasks.views import (
    show_my_tasks,
)  # Assuming show_my_tasks is defined in tasks.views


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(
                request,
                username=username,
                password=password,
            )
            if user is not None:
                login(request, user)
                return redirect("show_my_tasks")  # Adjust the redirect URL
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("login")  # Adjust the redirect URL


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(
                    username=username, password=password
                )
                login(request, user)
                return redirect("show_my_tasks")  # Adjust the redirect URL
            else:
                form.add_error(
                    "password_confirmation", "The passwords do not match."
                )
    else:
        form = SignUpForm()

    return render(request, "accounts/signup.html", {"form": form})

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Project
from .forms import ProjectForm


@login_required
def list_projects(request):
    projects = Project.objects.filter(owner=request.user)
    context = {"projects": projects}
    return render(request, "projects/list.html", context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, pk=id)
    tasks = project.tasks.all()
    context = {
        "project": project,
        "tasks": tasks,
    }
    return render(request, "projects/details.html", context)


@login_required
def create_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            Project = form.save()
            return redirect("home")
    else:
        form = ProjectForm()

    context = {
        "form": form,
    }
    return render(request, "projects/create_project.html", context)

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Task
from .forms import TaskForm


@login_required
def show_my_tasks(request):
    tasks = Task.objects.filter(assignee=request.user)
    return render(request, "show_my_tasks.html", {"tasks": tasks})


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(
                "projects_list"
            )  # Adjust the redirect URL as needed
    else:
        form = TaskForm()

    return render(request, "create_task.html", {"form": form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <main>
        <div>
            <form method="post">
                {% csrf_token %}
                <h1>Login</h1>
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
        </div>
    </main>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
    <main>
        <div>
            <h1>Signup</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Signup</button>
            </form>
        </div>
    </main>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Your App Title{% endblock %}</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
                    <li><a href="{% url 'list_projects' %}">My projects</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

</body>

</html>

projects/templates/projects/create_project.html
{% extends 'base.html' %}

{% block title %}Create a new project{% endblock %}

{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                
                <label for="id_name">Name:</label>
                <input type="text" name="name" id="id_name" required><br>
                
                <label for="id_description">Description:</label>
                <textarea name="description" id="id_description" required></textarea><br>
                
                <label for="id_owner">Owner:</label>
                <select name="owner" id="id_owner">
                    {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                    {% endfor %}
                </select><br>
                
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

projects/templates/projects/details.html
{% extends 'base.html' %}

{% block title %}{{ project.name }}{% endblock %}

{% block content %}
    <main>
        <div>
            <h1>{{ project.name }}</h1>
            <p>{{ project.description }}</p>

            <h2>Tasks</h2>
            {% if project.tasks.all %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.assignee.username }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block title %}Project List{% endblock %}

{% block content %}
    <main>
        <div>
            <h1>Project List</h1>
            {% if projects %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Owner</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>{{ project.name }}</td>
                                <td>{{ project.description }}</td>
                                <td>{{ project.owner.username }}</td>
                                <td>
                                    <a href="{% url 'show_project' project.id %}">Details</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No projects available</p>
            {% endif %}
        </div>
    </main>
{% endblock %}

tasks/templates/create_task.html
{% extends 'base.html' %}

{% block title %}Create Task{% endblock %}

{% block content %}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post" action="{% url 'create_task' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock %}

tasks/templates/project_detail.html
{% extends 'base.html' %}

{% block title %}Project Detail{% endblock %}

{% block content %}
    <header>
        <h1>Project Detail</h1>
    </header>

    <main>
        <h2>Tasks</h2>
        <a href="{% url 'create_task' %}">Create a new task</a>
    </main>
{% endblock %}

tasks/templates/show_my_tasks.html
{% extends 'base.html' %}

{% block title %}My Tasks{% endblock %}

{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if tasks %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td>{{ task.is_completed|yesno:"yes,no" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock %}